name: Node CI
on: [push]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    strategy:
      matrix:
        node-version: [12.18]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: |
        npm ci
      working-directory: ${{ env.working-directory }}
    - name: test
      run: |
        npm test
      working-directory: ${{ env.working-directory }}
  build-frontend:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    strategy:
      matrix:
        node-version: [12.18]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install dependencies
      run: |
        npm ci
      working-directory: ${{ env.working-directory }}
    - name: build
      run: |
        npm run build
      working-directory: ${{ env.working-directory }}
